CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 34 > cifar100_34.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 35 > cifar100_35.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 36 > cifar100_36.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 37 > cifar100_37.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 38 > cifar100_38.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 39 > cifar100_39.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 41 --random_seed 4140 > cifar100_4140.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 39 --random_seed 3941 > cifar100_3941.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                           --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 42 > cifar100_42.txt &     

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/42/simclr-cifar100-tgit3zut-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 43 > cifar100_43.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/42/simclr-cifar100-tgit3zut-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar100_44.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/42/simclr-cifar100-tgit3zut-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > cifar100_45.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/42/simclr-cifar100-tgit3zut-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > cifar100_46.txt &

CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/43/simclr-cifar100-1d7f87me-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar100_47.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/43/simclr-cifar100-1d7f87me-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > cifar100_48.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/43/simclr-cifar100-1d7f87me-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > cifar100_49.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/43/simclr-cifar100-1d7f87me-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > cifar100_50.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/44/simclr-cifar100-z7vq7o3l-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 51 > cifar100_51.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/44/simclr-cifar100-z7vq7o3l-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 52 > cifar100_52.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/44/simclr-cifar100-z7vq7o3l-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 53 > cifar100_53.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/44/simclr-cifar100-z7vq7o3l-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 54 > cifar100_54.txt &

CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/45/simclr-cifar100-p78xnkeq-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 55 > cifar100_55.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/45/simclr-cifar100-p78xnkeq-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 56 > cifar100_56.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/45/simclr-cifar100-p78xnkeq-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 57 > cifar100_57.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar100 --backbone resnet18 --data_dir ../data/cifar100 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar100/45/simclr-cifar100-p78xnkeq-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 58 > cifar100_58.txt &
