CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 34 > cifar10_34.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 35 > cifar10_35.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 36 > cifar10_36.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 37 > cifar10_37.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 38 > cifar10_38.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method random --pretrain_method simclr --target_class 0 --random_seed 39 > cifar10_39.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 40 > cifar10_40.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 41 > cifar10_41.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 42 > cifar10_42.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 7 --random_seed 742 > cifar10_742.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_43.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > cifar10_45.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > cifar10_46.txt &

CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > cifar10_48.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > cifar10_49.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > cifar10_50.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 51 > cifar10_51.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 52 > cifar10_52.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 53 > cifar10_53.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 54 > cifar10_54.txt &

CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 55 > cifar10_55.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 56 > cifar10_56.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 57 > cifar10_57.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 58 > cifar10_58.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10_/42/simclr-cifar10-b8vk3ui0-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 83 > cifar10_83.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10_/43/simclr-cifar10-1dktohdv-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 87 > cifar10_87.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10_/44/simclr-cifar10-shik76sa-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 91 > cifar10_91.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10_/45/simclr-cifar10-rslydi9a-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 95 > cifar10_95.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method dcs    --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_43.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method dcs    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47.txt &
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method dcs    --pretrain_method simclr --target_class 0 --random_seed 51 > cifar10_51.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method dcs    --pretrain_method simclr --target_class 0 --random_seed 55 > cifar10_55.txt &

CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method dcsneg --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_neg_43.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method dcsneg --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_neg_47.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method dcsneg --pretrain_method simclr --target_class 0 --random_seed 51 > cifar10_neg_51.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.6 --poison_method dcsneg --pretrain_method simclr --target_class 0 --random_seed 55 > cifar10_neg_55.txt &

CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 41 > cifar10_l0_41.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 1 --random_seed 42 > cifar10_l1_42.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 2 --random_seed 43 > cifar10_l2_43.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 3 --random_seed 44 > cifar10_l3_44.txt &
#0.5 rate
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.5 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 143 > cifar10_143.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.5 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 147 > cifar10_147.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.5 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 151 > cifar10_151.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.5 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 155 > cifar10_155.txt &
#0.1 rate
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.1 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 243 > cifar10_243.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.1 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 247 > cifar10_247.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.1 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 251 > cifar10_251.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.1 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 255 > cifar10_255.txt &

#0.5 rate
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.5 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 143 > cifar10knn_143.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.5 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 147 > cifar10knn_147.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.5 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 151 > cifar10knn_151.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.5 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 155 > cifar10knn_155.txt &
#0.1 rate
CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.1 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 243 > cifar10knn_243.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.1 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 247 > cifar10knn_247.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.1 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 251 > cifar10knn_251.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/45/simclr-cifar10-0rb9z0pa-ep=499.ckpt --poison_rate 0.1 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 255 > cifar10knn_255.txt &


# knn select k
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_44.txt &

CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > cifar10_k20_42.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_k20_43.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/44/simclr-cifar10-fn3yh7rp-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > cifar10_k20_44.txt &

CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method infonce --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_43_nce.txt &

CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method auto --pretrain_method simclr --target_class 0 --random_seed 43 > cifar10_43_nce.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > poison_result/cifar10_42_k05.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > poison_result/cifar10_43_k05.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > poison_result/cifar10_44_k05.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > poison_result/cifar10_45_k05.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > poison_result/cifar10_46_k05.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > poison_result/cifar10_47_k05.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > poison_result/cifar10_48_k05.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > poison_result/cifar10_49_k05.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > poison_result/cifar10_50_k05.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 51 > poison_result/cifar10_51_k05.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > poison_result/cifar10_42_k10.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > poison_result/cifar10_43_k10.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > poison_result/cifar10_44_k10.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > poison_result/cifar10_45_k10.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > poison_result/cifar10_46_k10.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > poison_result/cifar10_47_k10.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > poison_result/cifar10_48_k10.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > poison_result/cifar10_49_k10.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > poison_result/cifar10_50_k10.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 51 > poison_result/cifar10_51_k10.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > poison_result/cifar10_42_k11.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > poison_result/cifar10_43_k11.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > poison_result/cifar10_44_k11.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > poison_result/cifar10_45_k11.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > poison_result/cifar10_46_k11.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > poison_result/cifar10_47_k11.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > poison_result/cifar10_48_k11.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > poison_result/cifar10_49_k11.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > poison_result/cifar10_50_k11.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 51 > poison_result/cifar10_51_k11.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > poison_result/cifar10_42_k15.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > poison_result/cifar10_43_k15.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > poison_result/cifar10_44_k15.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > poison_result/cifar10_45_k15.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > poison_result/cifar10_46_k15.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > poison_result/cifar10_47_k15.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > poison_result/cifar10_48_k15.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > poison_result/cifar10_49_k15.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > poison_result/cifar10_50_k15.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 51 > poison_result/cifar10_51_k15.txt &

CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 42 > poison_result/cifar10_42_k20.txt &
CUDA_VISIBLE_DEVICES=1 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 43 > poison_result/cifar10_43_k20.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 44 > poison_result/cifar10_44_k20.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 45 > poison_result/cifar10_45_k20.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 46 > poison_result/cifar10_46_k20.txt &
CUDA_VISIBLE_DEVICES=5 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > poison_result/cifar10_47_k20.txt &
CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 48 > poison_result/cifar10_48_k20.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 49 > poison_result/cifar10_49_k20.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 50 > poison_result/cifar10_50_k20.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/43/simclr-cifar10-5sth1jr9-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 51 > poison_result/cifar10_51_k20.txt &
