CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.2 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_02.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.2 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_02.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.2 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_02.txt &

CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.4 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_04.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.4 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_04.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.4 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_04.txt &

CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.6 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_42.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_43.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_44.txt &

CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 0.8 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_08.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.8 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_08.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.8 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_08.txt &

CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor none                                                         --poison_rate 1.0 --poison_method clb    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_10.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 1.0 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_10.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 1.0 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 47 > cifar10_47_10.txt &
