CUDA_VISIBLE_DEVICES=0 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method simclr --target_class 0 --random_seed 63 > cifar10_63.txt &
CUDA_VISIBLE_DEVICES=2 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 64 > cifar10_64.txt &
CUDA_VISIBLE_DEVICES=3 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 65 > cifar10_65.txt &
CUDA_VISIBLE_DEVICES=4 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor my_zoo/simclr-cifar10/42/simclr-cifar10-ck74jbi5-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method simclr --target_class 0 --random_seed 66 > cifar10_66.txt &

CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/mocov2plus-cifar10/yfuxn7z0/mocov2plus-cifar10-yfuxn7z0-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method mocov2plus --target_class 0 --random_seed 67 > cifar10_67.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/mocov2plus-cifar10/yfuxn7z0/mocov2plus-cifar10-yfuxn7z0-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method mocov2plus --target_class 0 --random_seed 68 > cifar10_68.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/mocov2plus-cifar10/yfuxn7z0/mocov2plus-cifar10-yfuxn7z0-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method mocov2plus --target_class 0 --random_seed 69 > cifar10_69.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/mocov2plus-cifar10/yfuxn7z0/mocov2plus-cifar10-yfuxn7z0-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method mocov2plus --target_class 0 --random_seed 70 > cifar10_70.txt &

CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/byol-cifar10/bine9tna/byol-cifar10-bine9tna-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method byol --target_class 0 --random_seed 71 > cifar10_71.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/byol-cifar10/bine9tna/byol-cifar10-bine9tna-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method byol --target_class 0 --random_seed 72 > cifar10_72.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/byol-cifar10/bine9tna/byol-cifar10-bine9tna-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method byol --target_class 0 --random_seed 73 > cifar10_73.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/byol-cifar10/bine9tna/byol-cifar10-bine9tna-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method byol --target_class 0 --random_seed 74 > cifar10_74.txt &

CUDA_VISIBLE_DEVICES=6 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/barlow-cifar10/lwhsjghz/barlow-cifar10-lwhsjghz-ep=499.ckpt --poison_rate 0.6 --poison_method dcsnew --pretrain_method barlow_twins --target_class 0 --random_seed 75 > cifar10_75.txt &
CUDA_VISIBLE_DEVICES=7 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/barlow-cifar10/lwhsjghz/barlow-cifar10-lwhsjghz-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method barlow_twins --target_class 0 --random_seed 76 > cifar10_76.txt &
CUDA_VISIBLE_DEVICES=8 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/barlow-cifar10/lwhsjghz/barlow-cifar10-lwhsjghz-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method barlow_twins --target_class 0 --random_seed 77 > cifar10_77.txt &
CUDA_VISIBLE_DEVICES=9 nohup python main_4poison_new.py --dataset cifar10 --backbone resnet18 --data_dir ../data/cifar10 --train_dir train --optimizer sgd --pretrained_feature_extractor checkpoint/barlow-cifar10/lwhsjghz/barlow-cifar10-lwhsjghz-ep=499.ckpt --poison_rate 0.6 --poison_method knn    --pretrain_method barlow_twins --target_class 0 --random_seed 78 > cifar10_78.txt &
